spring:
  activate:
    on-profile: local
  sql:
    init:
      mode: always
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/testDB
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: none
      format_sql: true
    properties:
      hibernate:
        globally_quoted_identifiers: true
        dialect: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true

  thymeleaf:
    config.activate.on-profile: local
    prefix: classpath:/templates/
    suffix: html